# Generated by Django 4.1.3 on 2024-08-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
