# Generated by Django 4.1.3 on 2024-08-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='contraseña',
        ),
    ]
