# Generated by Django 4.1.3 on 2024-08-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0021_rename_telefono_usuario_contraseña'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
